export const ADD_VECHICLE='ADD_VECHICLE';
export const ADD_VECHICLE_SUCCES='ADD_VECHICLE_SUCCES';
export const ADD_VECHICLE_ERROR='ADD_VECHICLE_ERROR';

export const LIST_VECHICLE='LIST_VECHICLE';
export const LIST_VECHICLE_SUCCESS='LIST_VECHICLE_SUCCESS';
export const LIST_VECHICLE_ERROR='LIST_VECHICLE_ERROR';

export const GET_OBJECT_UPDATE='GET_OBJECT_UPDATE';

export const BUTTON_NEW='BUTTON_NEW';

export const EDIT_VECHICLE='EDIT_VECHICLE';
export const EDIT_VECHICLE_SUCCESS='EDIT_VECHICLE_SUCCESS';
export const EDIT_VECHICLE_ERROR='EDIT_VECHICLE_ERROR';

export const DELETE_VECHICLE_BEGIN='DELETE_VECHICLE_BEGIN';
export const DELETE_VECHICLE_ERROR='DELETE_VECHICLE_ERROR';
export const DELETE_VECHICLE_SUCCESS='DELETE_VECHICLE_SUCCESS';

export const TEST_LOAD='TEST_LOAD';










